### ISSUE TITLE
Unable to compile with libnotmuch 0.6.1-1 on Ubuntu 11.10

### ISSUE THREAD

**Issue by vortechs2000** [karelzak/mutt-kz#6]
I'm using the Ubuntu 11.10 (oneiric) version of libnotmuch-dev (0.6.1-1) and I get this error:

<pre>
gcc -DPKGDATADIR=\"/usr/local/share/mutt\" -DSYSCONFDIR=\"/usr/local/etc\" -DBINDIR=\"/usr/local/bin\" -DMUTTLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H=1 -I.  -I. -I. -I./imap  -Iintl -I./intl  -Wall -pedantic -Wno-long-long -g -O2 -MT mutt_notmuch.o -MD -MP -MF .deps/mutt_notmuch.Tpo -c -o mutt_notmuch.o mutt_notmuch.c
mutt_notmuch.c: In function ‘get_nm_message’:
mutt_notmuch.c:644:3: error: too many arguments to function ‘notmuch_database_find_message’
/usr/include/notmuch.h:316:1: note: declared here
make[2]: *** [mutt_notmuch.o] Error 1
make[2]: Leaving directory `/home/alewis/sandbox/mutt-kz'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/alewis/sandbox/mutt-kz'
make: *** [all] Error 2
</pre>

Is there a minimum version of notmuch required?  I didn't see one in the docs, but I could have missed it. 

Thanks!
